version: '3'

networks:
  app-network:

services:
  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./Docker/nginx/default.config/:/etc/nginx/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
        MYSQL_VERSION: 5.7
        MYSQL_DATABASE: my_database
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_PORT: 3306
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - ./mysql:/var/lib/mysql
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:900"
    networks:
      - app-network

